engine: localhost:9076
app: fossball
script: loadscript.qvs
connections:
  jdbc:
    type: jdbc
    name: jdbc
    username: root
    password: example
    settings:
      driver: mysql
      host: localhost
      port: 3306
      database: fossball